name: GitHub Classroom Workflow

on: push

permissions:
  checks: write
  issues: write
  actions: read
  contents: read

jobs:

  grading:
    if: ${{ !contains(github.actor, 'classroom') }}
    uses: BZZ-Commons/pygrader/.github/workflows/py_autograding.yml@main
    secrets: inherit
